# Site settings
title: "CS 341: System Programming"
email: angrave@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  "Webpage for Intelligent Access Lab at the University of Illinois at Urbana-Champaign."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angrave.github.io" # the base hostname & protocol for your site

exclude:
  [
    ".git",
    "README.md",
  ]


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
reveal:
  css_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/reveal.css"
  css_theme_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/theme/black.css"
  css_syntax_url: "/css/reveal-code-style.css"
  lib_head_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/lib/js/head.min.js"
  reveal_js_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/js/reveal.js"
plugins_dir:
  - _plugins
plugins:
  - jekyll-sitemap   # Search engine optimization
